### ISSUE TITLE
Downloading updates from accounts fails (TypeError: Cannot read property 'items' of undefined)

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider#100]
As the title states, downloading new photos/updates from accounts already added gets failed with the error in the attached images. However, adding a new account(user) download all pictures.

Account isnt rate limited nor are there any password issues on raider.

![image](https://user-images.githubusercontent.com/58679929/136690115-46672faa-ae16-4fba-b0db-ff23937b50c2.png)

**Comment by volvo917** [comment]
true for also new acounts
issues there as well
