### ISSUE TITLE
Question: Are developments efforts for Raider on hold/stopped?

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider#103]
I don't see Asset Kit pushing any updates to Raider any longer. Last update was in Jun and since then a lot has changed over at Instagram. I hope all's well with you/him.

Anyone has any updates?

**Comment by Osmiridium** [comment]
I'm wondering the same thing.

**Comment by dfsssssssgg** [comment]
The app is falling apart

**Comment by AssetKid** [comment]
See #110
