### ISSUE TITLE
Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider#53]
There is a comment in the report which states that it cannot read property 'items' of undefined. Is this a issue and is it impacting the downloads?

![image](https://user-images.githubusercontent.com/58679929/88932991-6e91c700-d29c-11ea-8976-2baf27b97613.png)

**Comment by denbartman** [comment]
I have a similar error, but when i get the error, downloading stops.
The only way to get the download running again is selecting the oldest site and download it manually, then after that automatic downloads starts again. (I think the error occurs always at the same accounts)
![image](https://user-images.githubusercontent.com/57780186/94604421-f6458300-0297-11eb-923e-548159f51cd7.png)

**Comment by denbartman** [comment]
I reverted back to 1.5.2 and the problem stays.
I notice the error occurs on sites that have not posts or story's for a long time.
The problem occurs since a few days.
Could it be something changed at instagram when nothing has to be dowloaded?

**Comment by supersick123** [comment]
> There is a comment in the report which states that it cannot read property 'items' of undefined. Is this a issue and is it impacting the downloads?
> 
> ![image](https://user-images.githubusercontent.com/58679929/88932991-6e91c700-d29c-11ea-8976-2baf27b97613.png)

I haven't experienced what @denbartman has, but I have seen the error message from @KaunWho. That error message appears when Raider tries to retrieve something but there is nothing to retrieve. By that, I mean, if I set Raider to download stories (and only stories) from my acc list, that error message will appear in the log whenever there are no stories to download for a particular account being scanned. I don't know if it's the same for images/videos, but it definitely applies to stories.

**Comment by KaunWho** [comment]
Closing, the app no longer works. Instagram has changed a lot of details.
