### ISSUE TITLE
Auto Close after updating pre-defined accounts

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider#83]
Instagram has been beefing up its API limits and keeps blocking automations. One thing I've found useful is to stop updating after the xx number of accounts have been updated. Along with the time limits and post limits if we can have a account limit it would help not getting locked out. Basically, an option to stop updating account post 100 accounts, or 50 accounts. Hopefully, its doable. Thanks!

**Comment by PascalSoftwares** [comment]
Very much agreed
